import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {randomUUID} from 'node:crypto';
const START=Date.parse('2026-09-16T01:00:00.000Z');
function mod(file,context){const module={exports:{}};vm.runInNewContext(readFileSync(file,'utf8'),{module,...context});return module.exports;}
const flush=()=>new Promise(r=>setImmediate(r));
function publicHarness(){let time=0,fail=false,hold=false,release;const calls=[],timers=new Map();const course={courseId:'synthetic-course',name:'合成课程',status:'scheduled',startAt:new Date(START).toISOString(),endAt:new Date(START+1000).toISOString(),localInput:{start:{local:'2026-09-16T09:00',offset:'+08:00'},end:{local:'2026-09-16T09:01',offset:'+08:00'}}};
 const snapshot={environment:'test',simulation:true,publicationRevision:1,state:'published',timeZone:'Asia/Taipei',coverage:{startAt:new Date(START-1000).toISOString(),endAt:new Date(START+86400000).toISOString()},courses:[course],days:[{date:'2026-09-16',state:'scheduled',covered:true,courses:[course]}]};
 const api={config:{environment:'test'},request:async path=>{calls.push(path);if(hold)await new Promise(r=>{release=r;});if(fail)throw{status:503};return{serverNow:new Date(START+time).toISOString(),data:structuredClone(snapshot)};}};
 const timing=mod('miniprogram/lib/observation-view.js',{Date,Intl});const page=mod('miniprogram/lib/schedule-public.js',{require:n=>n==='./session'?api:timing,wx:{getPerformance:()=>({now:()=>time})},setInterval:(fn,ms)=>{const id=randomUUID();timers.set(id,{fn,ms});return id;},clearInterval:id=>timers.delete(id),Date})();page.setData=d=>Object.assign(page.data,d);page.scheduleLoad();return{page,snapshot,calls,timers,now:v=>{time=v;},fail:v=>{fail=v;},hold:v=>{hold=v;},release:()=>release()};
}
test('S04 native public: no-login today/week, exact current-course end, empty/unpublished/withdrawn and offline history',async()=>{const h=publicHarness();h.page.scheduleShow();await flush();assert.equal(h.calls[0],'/schedule?view=today');assert.match(h.page.data.scheduleCurrent,/合成课程/);h.now(1000);h.page.scheduleRender();assert.match(h.page.data.scheduleCurrent,/不代表场地无人/);h.fail(true);await h.page.scheduleRefresh();assert.equal(h.page.data.scheduleHistory,true);assert.match(h.page.data.scheduleTitle,/上次获取/);assert.match(h.page.data.scheduleCurrent,/待确认/);h.fail(false);
 for(const state of ['empty','unpublished','withdrawn']){h.snapshot.days[0]={date:'2026-09-16',state,covered:state==='empty',courses:[]};h.snapshot.courses=[];h.snapshot.state=state==='empty'?'published':state;if(state==='unpublished')h.snapshot.coverage=null;await h.page.scheduleRefresh();assert.equal(h.page.data.scheduleDays[0].label,{empty:'该日无排课',unpublished:'课表尚未发布',withdrawn:'课表已撤回'}[state]);}h.page.scheduleChoose({currentTarget:{dataset:{view:'week'}}});await flush();assert.equal(h.calls.at(-1),'/schedule?view=week');});

test('S04 native public: one in-flight resource, hide clears polling, old response cannot replace new view',async()=>{const h=publicHarness();h.hold(true);h.page.scheduleShow();h.page.scheduleRefresh();h.page.scheduleRefresh();assert.equal(h.calls.length,1);assert.ok([...h.timers.values()].some(t=>t.ms===60000));h.page.scheduleHide();assert.equal(h.timers.size,0);h.page.scheduleChoose({currentTarget:{dataset:{view:'week'}}});h.page.scheduleShow();h.hold(false);h.release();await flush();await flush();assert.equal(h.calls.length,2);assert.equal(h.calls[1],'/schedule?view=week');assert.equal(h.page.data.scheduleHistory,false);});
function operatorHarness(){let page,modal,holdPath,release,failPath,failError,operationState='unknown';const store=new Map(),calls=[];const state={draftRevision:1,publicationRevision:'absent',publicationState:'unpublished',timeZone:'Asia/Taipei',draftTimeZone:'Asia/Taipei',coverage:{startDate:'2026-09-16',endDate:'2026-09-23'},courses:[],publishedCoverage:null};
 const api={config:{environment:'test',baseUrl:'http://127.0.0.1:8787'},load:()=> 'synthetic-token',clear:()=>store.clear(),operationId:async()=>randomUUID(),request:async(path,method,body)=>{calls.push({path,method,body});if(path===holdPath)await new Promise(r=>{release=r;});if(path===failPath)throw failError;let data=structuredClone(state);if(path.startsWith('/session?'))data={userId:'synthetic-op'};else if(path.startsWith('/operations/'))data={state:operationState};else if(path.endsWith('/time-preview'))data={startAt:'2026-09-16T01:00:00.000Z',endAt:'2026-09-16T02:00:00.000Z'};return{data,serverNow:new Date(START).toISOString()};}};
 vm.runInNewContext(readFileSync('miniprogram/pages/schedule-operator/index.js','utf8'),{require:()=>api,Page:p=>{page=p;},wx:{getStorageSync:k=>store.get(k),setStorageSync:(k,v)=>store.set(k,v),removeStorageSync:k=>store.delete(k),showModal:o=>{modal=o;}},setInterval:()=>1,clearInterval(){},Date});page.setData=d=>Object.assign(page.data,d);page.onLoad();
 return{page,api,state,calls,store,confirm:()=>modal.success({confirm:true}),refuse:()=>modal.success({confirm:false}),hold:path=>{holdPath=path;},release:()=>release(),fail:(path,error)=>{failPath=path;failError=error;},committed:()=>{operationState='committed';},input:(field,value)=>page.input({currentTarget:{dataset:{field}},detail:{value}})};
}
const action=name=>({currentTarget:{dataset:{action:name}}});
test('native operator: refusal and confirmation version/form changes never publish silently changed draft',async()=>{const h=operatorHarness();h.page.onShow();await flush();h.page.ask(action('publish'));h.refuse();await flush();assert.equal(h.calls.some(c=>c.path.endsWith('/publish')),false);h.page.ask(action('publish'));h.state.draftRevision=2;await h.page.refresh();h.confirm();await flush();assert.equal(h.calls.some(c=>c.path.endsWith('/publish')),false);assert.match(h.page.data.message,/重新确认/);h.page.ask(action('save'));h.input('endDate','2026-09-24');h.confirm();await flush();assert.equal(h.calls.some(c=>c.method==='PUT'),false);});

test('native operator: stable IDs in save/cancel, awaited preview hidden response cannot write; dirty conflicts retain edits',async()=>{const h=operatorHarness();h.page.onShow();await flush();await h.page.addCourse();const id=h.page.data.courses[0].courseId;Object.assign(h.page.data.courses[0],{name:'合成课程',startLocal:'2026-09-16T09:00',endLocal:'2026-09-16T10:00',startOffset:'+08:00',endOffset:'+08:00'});
 h.hold('/operator/schedule/time-preview');h.page.ask(action('save'));h.confirm();await flush();h.page.onHide();h.release();await flush();assert.equal(h.calls.some(c=>c.method==='PUT'),false);
 h.hold(null);h.page.onShow();await flush();h.page.data.courses[0].revision=1;h.page.cancelCourse({currentTarget:{dataset:{index:0}}});assert.equal(h.page.data.courses[0].courseId,id);assert.equal(h.page.data.courses[0].status,'cancelled');h.fail('/operator/schedule/draft',{status:409,code:'REVISION_CONFLICT'});h.page.ask(action('save'));h.confirm();await flush();await flush();assert.equal(h.page.data.courses[0].courseId,id);assert.equal(h.page.data.dirty,true);assert.equal(h.page.data.pending,false);assert.match(h.page.data.message,/未能确认|版本冲突/);});

test('I01 native operator unknown publication: persisted original key, query current state, same-key retry and committed refresh',async()=>{const h=operatorHarness();h.page.onShow();await flush();h.fail('/operator/schedule/publish',{code:'NETWORK_UNCONFIRMED'});h.page.ask(action('publish'));h.confirm();await flush();await flush();assert.equal(h.page.data.pending,true);const saved=[...h.store.values()][0];assert.equal(saved.body.replaceCoverageConfirmed,true);assert.equal(saved.body.expectedRevision.draft,1);await h.page.query();await flush();assert.equal(h.page.data.canRetry,true);h.fail(null);await h.page.retry();await flush();const writes=h.calls.filter(c=>c.path.endsWith('/publish'));assert.equal(writes.length,2);assert.equal(writes[0].body.operationId,writes[1].body.operationId);assert.equal(h.page.data.pending,false);
 h.fail('/operator/schedule/publish',{code:'NETWORK_UNCONFIRMED'});h.page.ask(action('publish'));h.confirm();await flush();await flush();h.committed();await h.page.query();await flush();assert.equal(h.page.data.pending,false);assert.equal(h.calls.at(-1).path,'/operator/schedule/draft');});


test('S02 native exact coverage end, selected outside/partially covered week and show immediately demotes old current course',async()=>{
 const h=publicHarness();h.page.scheduleShow();await flush();assert.match(h.page.data.scheduleCurrent,/合成课程/);h.page.scheduleHide();h.hold(true);h.page.scheduleShow();assert.equal(h.page.data.scheduleCurrent,'当前排课待确认');assert.equal(h.page.data.scheduleHistory,true);h.hold(false);h.release();await flush();
 h.snapshot.days.push({date:'2026-09-17',state:'unpublished',covered:false,courses:[]});await h.page.scheduleRefresh();assert.match(h.page.data.scheduleTitle,/部分日期/);assert.match(h.page.data.scheduleDays[1].label,/不在已发布覆盖/);
 h.now(86400000-1);h.page.scheduleRender();assert.doesNotMatch(h.page.data.scheduleTitle,/覆盖已结束/);h.now(86400000);h.page.scheduleRender();assert.equal(h.page.data.scheduleTitle,'课表覆盖已结束');assert.equal(h.page.data.scheduleCurrent,'课表覆盖已结束');
 h.now(0);h.snapshot.days=[{date:'2026-09-17',state:'unpublished',covered:false,courses:[]}];await h.page.scheduleRefresh();assert.match(h.page.data.scheduleTitle,/所选日期不在/);
});
