const api=require('../../lib/session');
const STORE='gym.operator-member-operation.v1',scope=()=>api.scope();
Page({
 data:{authorized:false,busy:false,code:'',memberRef:'',endDate:'',validUntilOverride:'',mode:'pending_confirmation',modes:['有效期待确认','固定结束日期','明确无固定期限'],modeIndex:0,confirmation:false,message:'',inspection:'',pending:false,canRetry:false,demo:!!(api.config.demo&&api.config.demo.enabled),testing:api.config.environment==='test'},
 onLoad(){this._generation=0;this._formRevision=0;try{const p=wx.getStorageSync(STORE);if(p&&p.scope===scope()){this._pending=p;this.setData({pending:true});}}catch(_){}},
 onShow(){try{const p=wx.getStorageSync(STORE);this._pending=p&&p.scope===scope()?p:null;}catch(_){this._pending=null;}this.setData({pending:!!this._pending});this._visible=true;this.checkRole();},
 onHide(){this._visible=false;this._generation++;this._intent=null;this._inspected=null;this.setData({authorized:false,code:'',memberRef:'',inspection:'',confirmation:false});},onUnload(){this.onHide();},
 async checkRole(){const generation=this._generation;try{const r=await api.request('/operator/role','GET',undefined,api.load());if(generation===this._generation)this.setData({authorized:r.data.isOperator,message:r.data.isOperator?(this.data.demo?'演示核验仅验证流程；请使用合成引用，不代表真实馆方核验。':'请在原馆系统核对，并当面比对用户配对请求。'):'没有馆方权限。'});}catch(_){if(generation===this._generation)this.setData({authorized:false,message:'请主动登录并确认馆方权限。'});}},
 form(){return {code:this.data.code,memberRef:this.data.memberRef,endDate:this.data.endDate,validUntilOverride:this.data.validUntilOverride,mode:this.data.mode,confirmation:this.data.confirmation};},
 input(e){this._formRevision++;this._inspected=null;this.setData({[e.currentTarget.dataset.field]:e.detail.value,inspection:'',confirmation:false});},
 chooseMode(e){this._formRevision++;const i=Number(e.detail.value);this.setData({modeIndex:i,mode:['pending_confirmation','fixed_until','no_fixed_expiry'][i],confirmation:false});this._inspected=null;},
 confirm(e){this._formRevision++;this.setData({confirmation:e.detail.value.length>0});},
 async expiry(form=this.form()){
  if(form.mode!=='fixed_until')return{mode:form.mode};
  if(form.validUntilOverride)return{mode:'fixed_until',localEndDate:form.endDate,validUntil:form.validUntilOverride};
  const result=await api.request('/operator/members/expiry-preview','POST',{localEndDate:form.endDate},api.load());
  return{mode:'fixed_until',localEndDate:result.data.localEndDate,validUntil:result.data.validUntil};
 },
 async inspect(){if(!this.data.authorized||this.data.busy)return;this.setData({busy:true});const generation=this._generation,revision=this._formRevision,form=this.form();try{const token=api.load();let pair=null;
  if(form.code)pair=(await api.request('/operator/pairing/lookup','POST',{code:form.code},token)).data;
  const result=await api.request('/operator/members/inspect','POST',{memberRef:form.memberRef,...(pair?{pairingId:pair.pairingId,code:form.code}:{})},token);
  if(generation!==this._generation||!this._visible||revision!==this._formRevision)return;this._inspected={...result.data,pair,serverNow:result.serverNow};this.setData({inspection:'资格：'+result.data.registry.state+'；当前关联：'+result.data.currentBinding.state+(pair?'；请求标识：'+pair.requesterLabel:''),message:'核对结果不是核验成功。请检查原系统和当面请求后明确确认。'});
 }catch(e){if(generation===this._generation&&revision===this._formRevision)this.handleError(e);}finally{this.setData({busy:false});}},
 act(e){const action=e.currentTarget.dataset.action;if(!['bind','restore','reverify','revoke'].includes(action)||!this.data.authorized||!this._inspected||this.data.busy||this._pending)return;
  const target={revision:this._formRevision,inspection:this._inspected,generation:this._generation};wx.showModal({title:'确认馆方核验',content:action==='revoke'?'撤销本应用会员资格，关联槽位仍保留。':'你已当面核对当前请求（如适用）和原馆会员凭据，并确认所填有效期？',success:r=>{if(r.confirm)this.submit(action,target);}});},
 async submit(action,target={revision:this._formRevision,inspection:this._inspected,generation:this._generation}){if(!this.data.authorized||!this._inspected||this.data.busy||this._pending)return;if(target.revision!==this._formRevision||target.inspection!==this._inspected||target.generation!==this._generation){this._inspected=null;this.setData({message:'确认期间表单或核对结果已变化，请重新核对。'});return;}const form=this.form();this.setData({busy:true});const generation=this._generation;
  try{const i=this._inspected,token=api.load(),s=await api.request('/session?interaction=poll','GET',undefined,token);let path='/operator/members/',type='membership.'+action;
   let body={operationId:await api.operationId(),requestCreatedAt:s.serverNow,expectedRevision:{binding:i.currentBinding.revision,registry:i.registry.revision}};
   if(action==='bind'||action==='restore'){if(!i.pair)throw{status:422};path+=action;body={...body,expectedRevision:{pairing:i.pair.revision,binding:i.requesterBinding.revision,registry:i.registry.revision},pairingId:i.pair.pairingId,code:form.code,memberRef:form.memberRef,frontDeskConfirmed:form.confirmation,expiry:await this.expiry(form)};}
   else{if(!i.currentBinding.id)throw{status:422};path+=i.currentBinding.id+'/'+action;if(action==='revoke')body.reasonCategory='qualification-withdrawn';else Object.assign(body,{memberRef:form.memberRef,frontDeskConfirmed:form.confirmation,expiry:await this.expiry(form),reasonCategory:'renewal'});}
   if(generation!==this._generation||!this._visible)return;if(target.revision!==this._formRevision||target.inspection!==this._inspected)throw{status:409};
   const pending={scope:scope(),userId:s.data.userId,key:body.operationId,type,path};wx.setStorageSync(STORE,pending);this._pending=pending;this._intent=body;this.setData({pending:true});await api.request(path,'POST',body,token);if(generation!==this._generation||!this._visible)return;this.clearPending();this._inspected=null;this.setData({message:'操作已提交；请重新精确核对当前状态，勿以旧结果当资格。',code:'',memberRef:'',inspection:'',confirmation:false});
  }catch(e){if(generation===this._generation)this.handleError(e);}finally{this.setData({busy:false});}
 },
 clearPending(){this._pending=null;this._intent=null;try{wx.removeStorageSync(STORE);}catch(_){}this.setData({pending:false,canRetry:false});},
 handleError(e){if(['TIMEZONE_AMBIGUOUS','TIMEZONE_NONEXISTENT'].includes(e.code)){this.setData({message:'门店该日期午夜不存在或有歧义，请按馆方确认填写明确UTC截止时刻，不能猜测。'});return;}if([400,409,410,422].includes(e.status)){this.clearPending();this._inspected=null;this.setData({message:'核验失败、版本冲突或请求无效。请重新查询并核对，不能覆盖旧关联。',confirmation:false});}else if([401,403].includes(e.status))this.setData({authorized:false,message:'当前无权操作，请重新登录或联系负责人。'});else this.setData({message:'结果待确认，请查询原操作；不会自动换key。'});},
 async query(){if(!this._pending||this.data.busy)return;this.setData({busy:true});try{const token=api.load(),s=await api.request('/session?interaction=poll','GET',undefined,token);if(s.data.userId!==this._pending.userId)throw{status:403};const p=this._pending,r=await api.request('/operations/'+p.key+'?type='+p.type,'GET',undefined,token);if(r.data.state==='committed'){this.clearPending();this._inspected=null;this.setData({message:'原操作已提交。请重新查询当前登记，不复用历史资格。',code:'',memberRef:'',inspection:''});}else this.setData({canRetry:true,message:'未找到可确认结果。可用原表单重试；表单已清除或超时则需重新现场核对。'});}catch(e){this.handleError(e);}finally{this.setData({busy:false});}},
 async retry(){if(!this._pending||!this.data.canRetry||this.data.busy)return;if(!this._intent){this.setData({message:'原始核验资料未保存。请重新查询当前登记并明确重新核对。'});return;}this.setData({busy:true});try{const token=api.load(),s=await api.request('/session?interaction=poll','GET',undefined,token);if(s.data.userId!==this._pending.userId)throw{status:403};if(Date.parse(s.serverNow)-Date.parse(this._intent.requestCreatedAt)>300000)throw{status:422};await api.request(this._pending.path,'POST',this._intent,token);this.clearPending();this._inspected=null;this.setData({message:'操作已提交，请重新查询当前状态。',code:'',memberRef:'',inspection:''});}catch(e){this.handleError(e);}finally{this.setData({busy:false});}},
 restart(){if(!this.data.canRetry||this.data.busy)return;wx.showModal({title:'重新核对',content:'重新查询当前登记与配对请求，核实原系统后再确认新操作。',success:r=>{if(r.confirm){this.clearPending();this._inspected=null;this.setData({confirmation:false,inspection:''});}}});}
});
