const api=require('../../lib/session');
const KEY='gym.schedule-operation.v1',scope=()=>api.config.environment+':'+api.config.baseUrl,clone=x=>JSON.parse(JSON.stringify(x));
Page({
 data:{authorized:false,busy:false,dirty:false,pending:false,canRetry:false,message:'',startDate:'',endDate:'',courses:[],timeZone:'',publishedCoverage:'尚未发布',testing:api.config.environment==='test'},
 onLoad(){this._generation=0;this._form=0;},
 onShow(){this._visible=true;try{const p=wx.getStorageSync(KEY);this._pending=p&&p.scope===scope()?p:null;}catch(_){this._pending=null;}this.setData({pending:!!this._pending,authorized:false});this.refresh();this._poll=setInterval(()=>this.refresh(),60000);},
 onHide(){this._visible=false;this._generation++;clearInterval(this._poll);this.setData({authorized:false});},onUnload(){this.onHide();},
 accept(s){this._base=clone(s);this._form++;this.setData({dirty:false,startDate:s.coverage?s.coverage.startDate:'',endDate:s.coverage?s.coverage.endDate:'',courses:s.courses.map(x=>({...x,startLocal:x.localInput.start.local,startOffset:x.localInput.start.offset,endLocal:x.localInput.end.local,endOffset:x.localInput.end.offset}))});},
 async refresh(){if(!this._visible)return;if(this._reading||this.data.busy){this._queued=true;return;}this._reading=true;const g=this._generation;try{const r=await api.request('/operator/schedule/draft','GET',undefined,api.load());if(g!==this._generation||!this._visible)return;this._latest=r.data;this._serverNow=r.serverNow;this.setData({authorized:true,timeZone:r.data.timeZone,publishedCoverage:r.data.publishedCoverage?r.data.publishedCoverage.startDate+' 至 '+r.data.publishedCoverage.endDate+'（止日不含）':r.data.publicationState==='withdrawn'?'已撤回':'尚未发布'});if(!this.data.dirty&&!this._pending)this.accept(r.data);}catch(e){if(g===this._generation)this.error(e,false);}finally{this._reading=false;const q=this._queued;this._queued=false;if(q&&this._visible)this.refresh();}},
 input(e){if(this.data.busy||this._pending)return;this._form++;this.setData({[e.currentTarget.dataset.field]:e.detail.value,dirty:true});},
 courseInput(e){if(this.data.busy||this._pending)return;const courses=clone(this.data.courses),{index,field}=e.currentTarget.dataset;courses[index][field]=e.detail.value;this._form++;this.setData({courses,dirty:true});},
 async addCourse(){if(this.data.busy||this._pending||!this.data.authorized)return;const g=this._generation;this.setData({busy:true});try{const courseId=await api.operationId();if(g!==this._generation||!this._visible)return;this._form++;this.setData({dirty:true,courses:[...this.data.courses,{courseId,revision:'absent',name:'',status:'scheduled',startLocal:'',endLocal:'',startOffset:'',endOffset:''}]});}catch(e){this.error(e,false);}finally{this.setData({busy:false});}},
 cancelCourse(e){if(this.data.busy||this._pending)return;const courses=clone(this.data.courses),n=Number(e.currentTarget.dataset.index);if(courses[n].revision==='absent')courses.splice(n,1);else courses[n].status='cancelled';this._form++;this.setData({dirty:true,courses});},
 dropOutside(e){if(this.data.busy||this._pending)return;const n=Number(e.currentTarget.dataset.index),revision=this._form,g=this._generation;wx.showModal({title:'移出新覆盖范围',content:'仅允许移除不与新覆盖范围相交的旧课程；范围内课程须保留取消标记。',success:r=>{if(r.confirm&&revision===this._form&&g===this._generation&&this._visible){const courses=clone(this.data.courses);courses.splice(n,1);this._form++;this.setData({courses,dirty:true});}}});},
 reload(){if(this.data.busy||this._pending)return;const form=this._form,g=this._generation;wx.showModal({title:'重新读取草稿',content:'放弃当前未保存编辑，使用服务器最新草稿？',success:r=>{if(r.confirm&&form===this._form&&g===this._generation&&this._visible){this.setData({dirty:false});this.refresh();}}});},
 ask(e){const action=e.currentTarget.dataset.action;if(!['save','publish','withdraw'].includes(action)||!this.data.authorized||this.data.busy||this._pending||!this._base)return;if(action==='publish'&&this.data.dirty){this.setData({message:'请先保存草稿，再确认发布。'});return;}const target={form:this._form,base:clone(this._base),generation:this._generation,token:api.load(),startDate:this.data.startDate,endDate:this.data.endDate,courses:clone(this.data.courses)};
 wx.showModal({title:action==='publish'?'确认整体替换公开课表':'确认课表操作',content:action==='publish'?'当前覆盖：'+this.data.publishedCoverage+'；替换为 '+target.startDate+' 至 '+target.endDate+'（止日不含）。退出覆盖日期将尚未发布。':action==='withdraw'?'撤回当前公开课表，不恢复旧版本。':'保存完整草稿；不会改变公开课表。',success:r=>{if(r.confirm)this.submit(action,target);}});},
 matches(t){return this._visible&&t.generation===this._generation&&t.form===this._form&&t.token===api.load()&&this._base&&t.base.draftRevision===this._base.draftRevision&&t.base.publicationRevision===this._base.publicationRevision;},
 async submit(action,target){if(this.data.busy||this._pending||!this.matches(target)){this.setData({message:'确认期间内容或版本已变化，请重新确认。'});return;}this.setData({busy:true});const g=this._generation;try{const token=api.load(),session=await api.request('/session?interaction=poll','GET',undefined,token);let body={operationId:await api.operationId(),requestCreatedAt:session.serverNow,expectedRevision:target.base.draftRevision};
 if(action==='save'){const courses=[];for(const item of target.courses){const localInput={start:{local:item.startLocal,offset:item.startOffset},end:{local:item.endLocal,offset:item.endOffset}},p=await api.request('/operator/schedule/time-preview','POST',localInput,token);courses.push({courseId:item.courseId,revision:item.revision,name:item.name,status:item.status,localInput,...p.data});}body={...body,coverage:{startDate:target.startDate,endDate:target.endDate},courses};}
 else if(action==='publish'){body.expectedRevision={draft:target.base.draftRevision,publication:target.base.publicationRevision};body.replaceCoverageConfirmed=true;}else{body.expectedRevision=target.base.publicationRevision;body.reasonCategory='correction';}
 if(!this.matches(target))throw{status:409};const pending={scope:scope(),userId:session.data.userId,body,type:'schedule.'+(action==='save'?'draft.save':action),path:'/operator/schedule/'+(action==='save'?'draft':action),method:action==='save'?'PUT':'POST'};wx.setStorageSync(KEY,pending);this._pending=pending;this.setData({pending:true});await this.send(token,g);
 }catch(e){if(g===this._generation)this.error(e,true);}finally{this.setData({busy:false});if(this._visible)this.refresh();}},
 clear(){this._pending=null;try{wx.removeStorageSync(KEY);}catch(_){}this.setData({pending:false,canRetry:false});},
 async send(token,g){const p=this._pending;await api.request(p.path,p.method,p.body,token);if(g!==this._generation||!this._visible)return;this.clear();this.setData({dirty:false,message:'操作已提交，正在读取当前版本。'});},
 error(e,write){if(e.status===401){api.clear();this._pending=null;this.setData({authorized:false,pending:false,message:'登录失效，请主动重新登录。'});}else if(e.status===403)this.setData({authorized:false,message:'当前没有课表维护权限。'});else if(write&&[400,409,410,422].includes(e.status)){this.clear();this.setData({message:e.status===409?'版本冲突；编辑已保留，请核对最新草稿再明确重新编辑。':'输入或期限无效：'+(e.code||'请核对日期、偏移和课程')+'。编辑已保留。'});}else this.setData({message:write&&this._pending?'结果待确认，请查询原操作，不自动换key。':'未能确认最新课表，请刷新重试。'});},
 async query(){if(!this._pending||this.data.busy||!this._visible)return;this.setData({busy:true});const g=this._generation;try{const p=this._pending,token=api.load(),s=await api.request('/session?interaction=poll','GET',undefined,token);if(s.data.userId!==p.userId)throw{status:403};const r=await api.request('/operations/'+p.body.operationId+'?type='+p.type,'GET',undefined,token);if(g!==this._generation||!this._visible)return;if(r.data.state==='committed'){this.clear();this.setData({dirty:false,message:'原操作已提交，读取当前版本。'});}else this.setData({canRetry:true,message:'结果未知不代表回滚；先核对当前状态，再重试原请求或明确重新编辑。'});}catch(e){if(g===this._generation)this.error(e,false);}finally{this.setData({busy:false});this.refresh();}},
 async retry(){if(!this._pending||!this.data.canRetry||this.data.busy||!this._visible)return;this.setData({busy:true});const g=this._generation;try{const p=this._pending,token=api.load(),s=await api.request('/session?interaction=poll','GET',undefined,token);if(s.data.userId!==p.userId)throw{status:403};if(Date.parse(s.serverNow)-Date.parse(p.body.requestCreatedAt)>300000){this.setData({message:'原请求已超时，请核对当前状态并明确重新编辑。'});return;}if(g===this._generation)await this.send(token,g);}catch(e){if(g===this._generation)this.error(e,true);}finally{this.setData({busy:false});this.refresh();}},
 restart(){if(!this._pending||!this.data.canRetry||this.data.busy)return;const pending=this._pending,g=this._generation;wx.showModal({title:'重新核对草稿',content:'先核对当前服务器状态；旧结果未知不表示未提交。放弃旧请求并重新编辑？',success:r=>{if(r.confirm&&this._visible&&g===this._generation&&pending===this._pending){this.clear();this.setData({dirty:false});this.refresh();}}});}
});
