const api=require('./session'),timing=require('./observation-view');
function mono(){try{return wx.getPerformance().now();}catch(_){return null;}}
function coverageMessage(s,time){if(s.state==='withdrawn')return '课表已撤回';if(!s.coverage)return '课表尚未发布';if(time>=Date.parse(s.coverage.endAt))return '课表覆盖已结束';if(time<Date.parse(s.coverage.startAt))return '已发布覆盖尚未开始';return '所选日期不在已发布覆盖范围';}
const labels={unpublished:'课表尚未发布',withdrawn:'课表已撤回',empty:'该日无排课',scheduled:'按课表排课'};
module.exports=function(){return{
 data:{scheduleView:'today',scheduleTitle:'正在获取课表',scheduleDays:[],scheduleCurrent:'当前排课待确认',scheduleHistory:false,scheduleRefreshing:false,scheduleZone:''},
 scheduleLoad(){this._sg=0;this._sc=timing.clock(mono);},
 scheduleShow(){this._sv=true;this._sc.reset();this._so=false;this.scheduleRender();this.scheduleRefresh();this._sp=setInterval(()=>this.scheduleRefresh(),60000);this._st=setInterval(()=>this.scheduleRender(),1000);},
 scheduleHide(){this._sv=false;this._sg++;this._sc.reset();clearInterval(this._sp);clearInterval(this._st);},
 scheduleChoose(e){const view=e.currentTarget.dataset.view;if(!['today','week'].includes(view)||view===this.data.scheduleView)return;this._sg++;this.setData({scheduleView:view,scheduleDays:[],scheduleTitle:'正在获取课表',scheduleCurrent:'当前排课待确认'});this._ss=null;this.scheduleRefresh();},
 scheduleRender(){if(!this._sv)return;const s=this._ss,time=this._sc.now();if(!s)return;const live=this._so&&time!==null;const covered=s.coverage&&time>=Date.parse(s.coverage.startAt)&&time<Date.parse(s.coverage.endAt);const current=live&&covered?s.courses.filter(x=>x.status==='scheduled'&&Date.parse(x.startAt)<=time&&time<Date.parse(x.endAt)):[];
 this.setData({scheduleTitle:live?(s.state==='withdrawn'||!s.coverage||time>=Date.parse(s.coverage.endAt)||s.days.every(d=>!d.covered)?coverageMessage(s,time):s.days.some(d=>!d.covered)?'部分日期已发布；其他日期尚未覆盖':'馆方发布课表'):'未能确认最新变更；以下仅为上次获取记录',scheduleHistory:!live,scheduleZone:s.timeZone,scheduleCurrent:!live?'当前排课待确认':current.length?'按课表进行中：'+current.map(x=>x.name).join('、'):covered?'当前无进行中排课（不代表场地无人）':coverageMessage(s,time),scheduleDays:s.days.map(d=>({...d,label:!d.covered&&s.state!=='withdrawn'&&s.coverage?'该日期不在已发布覆盖范围':labels[d.state],courses:d.courses.map(x=>({...x,timeText:x.localInput.start.local.replace('T',' ')+' '+x.localInput.start.offset+' → '+x.localInput.end.local.replace('T',' ')+' '+x.localInput.end.offset,statusText:x.status==='cancelled'?'已取消':'按课表安排'}))}))});},
 async scheduleRefresh(){if(!this._sv)return;if(this._sr){this._sq=true;return;}this._sr=true;const generation=this._sg;this.setData({scheduleRefreshing:true});try{const start=mono(),r=await api.request('/schedule?view='+this.data.scheduleView,'GET');if(generation!==this._sg||!this._sv)return;if(!r.data||r.data.environment!==api.config.environment||!Array.isArray(r.data.days)||!Array.isArray(r.data.courses)||(api.config.environment==='store'&&r.data.simulation)||!r.data.days.every(d=>Array.isArray(d.courses)))throw{code:'INVALID_RESPONSE'};this._ss=r.data;this._sc.accept(r.serverNow,start);this._so=true;this.scheduleRender();}catch(_){if(generation===this._sg&&this._sv){this._so=false;this._sc.reset();this.setData({scheduleTitle:'未能确认最新变更，请刷新重试',scheduleCurrent:'当前排课待确认',scheduleHistory:true});this.scheduleRender();}}finally{this._sr=false;this.setData({scheduleRefreshing:false});const queued=this._sq;this._sq=false;if(queued&&this._sv)this.scheduleRefresh();}}
};};
